name: fluttertfirst
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^8.0.3
  provider: ^6.1.2
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  razorpay_flutter: ^1.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true



